Repository pingSubhajit/letraz, pull requests merged in 2024-10, with the labels that each got.

#14 comp: building the pop confirm component
  components/onboarding/Education.tsx
  components/ui/pop-confirm.tsx
  components/ui/popover.tsx
  package.json
  yarn.lock
Labels: Component

#15 feat: functionality to remove added educations from the onboarding screen
  components/onboarding/Education.tsx
  components/onboarding/EducationForm.tsx
  lib/education.methods.ts
Labels: Feature

#16 feat: functionality to remove added past experiences from the onboarding screen
  components/onboarding/Education.tsx
  components/onboarding/Experience.tsx
  components/onboarding/ExperienceForm.tsx
  lib/experience.methods.ts
Labels: Feature

#12 core: Migration to Next v15
  app/(auth)/signin/[[...sign-in]]/SignInPage.title.tsx
  app/app/craft/page.tsx
  app/app/onboarding/BrainAnimation.client.tsx
  app/app/onboarding/page.tsx
  app/page.description.tsx
  app/page.heading.tsx
  app/page.logo.tsx
  app/page.tsx
  components/NewResumeInput.tsx
  components/Waitlist.tsx
  components/animations/TextAnimations.tsx
  components/clientContainers/AppSidebarContainer.tsx
  components/onboarding/About.tsx
  components/onboarding/AboutDescription.tsx
  components/onboarding/Education.tsx
  components/onboarding/EducationForm.tsx
  components/onboarding/Experience.tsx
  components/onboarding/ExperienceForm.tsx
  components/onboarding/OnboardingFormInput.tsx
  components/onboarding/PersonalDetails.tsx
  components/onboarding/PersonalDetailsForm.tsx
  components/onboarding/Welcome.tsx
  components/resume/ResumeView.tsx
  components/ui/dialog.tsx
  components/ui/form.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/select.tsx
  components/ui/sonner.tsx
  components/utilities/AiLoading.tsx
  config.ts
  db/drizzle.ts
  declarations.d.ts
  drizzle.config.ts
  emails/welcome.tsx
  middleware.ts
  package.json
  postcss.config.mjs
  yarn.lock
Labels: Core

#20 fix: @clerk/nextjs migration to support Next.js v15
  app/app/onboarding/page.tsx
  components/onboarding/BaseResume.tsx
  middleware.ts
  package.json
  yarn.lock
Labels: bug
