Repository pingSubhajit/letraz, pull requests merged in 2025-07, with the labels that each got.

#54 LET-42 | chore: Recommendation on feasibility of using LaTeX as primary rendering method
  documents/Recommendation Document_ Feasibility of Using LaTeX for Resume Rendering.pdf
Labels: Core

#130 LET-94 | feat: functionality to reorder resume sections and section
  bun.lockb
  components/resume/ReorderableSections.tsx
  components/resume/ResumeViewer.tsx
  components/resume/controllers/EducationController.tsx
  components/resume/controllers/ExperienceController.tsx
  components/resume/controllers/PersonalInfoController.tsx
  components/resume/editors/EducationEditor.tsx
  components/resume/editors/ExperienceEditor.tsx
  components/resume/themes/DEAFULT_THEME/DefaultTheme.tsx
  components/resume/themes/DEAFULT_THEME/sections/EducationSection.tsx
  components/resume/themes/DEAFULT_THEME/sections/ExperienceSection.tsx
  components/resume/themes/DEAFULT_THEME/sections/PersonalInfoSection.tsx
  components/resume/themes/DEFAULT_THEME/DefaultTheme.tsx
  components/resume/themes/DEFAULT_THEME/sections/EducationSection.tsx
  components/resume/themes/DEFAULT_THEME/sections/EducationTitle.tsx
  components/resume/themes/DEFAULT_THEME/sections/ExperienceSection.tsx
  components/resume/themes/DEFAULT_THEME/sections/ExperienceTitle.tsx
  components/resume/themes/DEFAULT_THEME/sections/PersonalInfoSection.tsx
  components/resume/themes/DEFAULT_THEME/shared/Components.tsx
  components/resume/themes/ThemeFactory.tsx
  lib/resume/actions.ts
  lib/resume/mutations.ts
  package.json
Labels: Feature, Component, Logic

#152 LET-112 | feat: beta-access email and follow-up email
  emails/follow-up-access.tsx
  emails/welcome-to-beta.tsx
Labels: Component, Core

#154 LET-113 | core: Implement a seamless transition between the onboarding and the dashboard
  app/(auth)/signup/[[...sign-up]]/page.tsx
  app/app/onboarding/types.ts
  app/app/page.tsx
  app/layout.tsx
  components/AppSidebar.tsx
  components/NewResumeInput.tsx
  components/OnboardingWelcome.tsx
  components/onboarding/About.tsx
  components/onboarding/BaseResume.tsx
  components/onboarding/BaseResumeProvider.tsx
  components/onboarding/EducationForm.tsx
  components/onboarding/ExperienceForm.tsx
  components/onboarding/OnboardingCompletionButton.tsx
  components/onboarding/PersonalDetailsForm.tsx
  components/onboarding/Welcome.tsx
  lib/onboarding/actions.ts
  lib/onboarding/globals.d.ts
  lib/onboarding/hooks.ts
  lib/onboarding/types.ts
  middleware.ts
Labels: Component, Core, Logic

#159 LET-102 | comp: CertificationEditor for ResumeEditor component
  components/resume/ResumeEditor.tsx
  components/resume/editors/CertificationEditor.tsx
  lib/certification/actions.ts
  lib/certification/keys.ts
  lib/certification/mutations.ts
  lib/certification/queries.ts
  lib/certification/types.ts
Labels: Feature, Component

#162 LET 108 | feat(editor): Add feature flag for new resume editor tabs design
  .env.example
  components/resume/ResumeEditor.tsx
  components/resume/editors/CertificationEditor.tsx
  components/resume/editors/EducationEditor.tsx
  components/resume/editors/ExperienceEditor.tsx
  components/resume/editors/PersonalDetailsEditor.tsx
  components/resume/editors/SkillsEditor.tsx
  components/ui/tabs.tsx
  env.ts
Labels: Component, Core, Logic

#164 LET 36 | core: skills section for default resume theme
  components/resume/controllers/SkillsController.tsx
  components/resume/editors/SkillsEditor.tsx
  components/resume/themes/DEFAULT_THEME/DefaultTheme.tsx
  components/resume/themes/DEFAULT_THEME/sections/SkillsSection.tsx
  components/resume/themes/DEFAULT_THEME/sections/SkillsTitle.tsx
  components/resume/themes/DEFAULT_THEME/styles.css
  components/resume/themes/ThemeFactory.tsx
  lib/resume/types.ts
Labels: Feature, Component, Style

#167 LET-90 | comp: Loading indicator for ResumeEditors and ResumeView
  components/animations/DefaultFade.ts
  components/resume/ResumeEditor.tsx
  components/resume/ResumeView.tsx
  components/resume/editors/CertificationEditor.tsx
  components/resume/editors/EducationEditor.tsx
  components/resume/editors/ExperienceEditor.tsx
  components/resume/editors/PersonalDetailsEditor.tsx
  components/resume/editors/ProjectEditor.tsx
  components/resume/editors/SkillsEditor.tsx
  components/skeletons/CertificationEditorSkeleton.tsx
  components/skeletons/EducationEditorSkeleton.tsx
  components/skeletons/ExperienceEditorSkeleton.tsx
  components/skeletons/PersonalDetailsEditorSkeleton.tsx
  components/skeletons/ProjectEditorSkeleton.tsx
  components/skeletons/ResumeEditorSkeleton.tsx
  components/skeletons/ResumeViewerSkeleton.tsx
  components/skeletons/SkillsEditorSkeleton.tsx
  components/skeletons/shared/EditorHeaderSkeleton.tsx
  components/skeletons/shared/EditorListSkeleton.tsx
  components/skeletons/shared/FormSkeleton.tsx
  components/skeletons/shared/ItemCardSkeleton.tsx
Labels: Component, Improvement, Style

#171 LET-118 | core: Refactor skill types to accommodate for the changed structure of backend response
  components/resume/controllers/SkillsController.tsx
  components/resume/themes/ThemeFactory.tsx
  lib/resume/types.ts
  lib/skill/types.ts
Labels: Core, Logic

#172 LET-20 | core: Certification section for the default theme
  components/resume/controllers/CertificationController.tsx
  components/resume/themes/DEFAULT_THEME/DefaultTheme.tsx
  components/resume/themes/DEFAULT_THEME/sections/CertificationSection.tsx
  components/resume/themes/DEFAULT_THEME/sections/CertificationTitle.tsx
  components/resume/themes/DEFAULT_THEME/styles.css
  components/resume/themes/ThemeFactory.tsx
Labels: Feature, Component, Core

#175 LET-119 | bug: Resume viewer not loading due to parser mismatch of expected and real data of resume object
  lib/job/types.ts
  lib/resume/__tests__/actions.test.ts
  lib/resume/__tests__/queries.test.ts
  lib/resume/types.ts
  middleware.ts
Labels: bug, Component, Core

#173 LET 115 | impr: resume editor improvements
  components/resume/ResumeView.tsx
  components/resume/contexts/ResumeHighlightContext.tsx
  components/resume/controllers/CertificationController.tsx
  components/resume/controllers/EducationController.tsx
  components/resume/controllers/ExperienceController.tsx
  components/resume/controllers/ProjectController.tsx
  components/resume/editors/CertificationEditor.tsx
  components/resume/editors/EducationEditor.tsx
  components/resume/editors/ExperienceEditor.tsx
  components/resume/editors/PersonalDetailsEditor.tsx
  components/resume/editors/ProjectEditor.tsx
  components/resume/editors/SkillsEditor.tsx
  components/resume/hooks/useAutoFocus.ts
  components/resume/themes/DEFAULT_THEME/sections/CertificationSection.tsx
  components/resume/themes/DEFAULT_THEME/sections/EducationSection.tsx
  components/resume/themes/DEFAULT_THEME/sections/EducationTitle.tsx
  components/resume/themes/DEFAULT_THEME/sections/ExperienceSection.tsx
  components/resume/themes/DEFAULT_THEME/sections/ExperienceTitle.tsx
  components/resume/themes/DEFAULT_THEME/sections/PersonalInfoSection.tsx
  components/resume/themes/DEFAULT_THEME/sections/ProjectsSection.tsx
  components/resume/themes/DEFAULT_THEME/sections/ProjectsTitle.tsx
  components/resume/themes/DEFAULT_THEME/sections/SkillsSection.tsx
  components/resume/themes/DEFAULT_THEME/sections/SkillsTitle.tsx
  components/resume/themes/ThemeFactory.tsx
Labels: Feature, Component, Logic, Improvement
