Repository pingSubhajit/letraz, pull requests merged in 2025-02, with the labels that each got.

#98 LET-39 | refactor: Update nextjs frontend lib methods to use the
  .env.example
  app/app/craft/page.tsx
  app/app/onboarding/page.tsx
  bun.lockb
  components/JobSummary.tsx
  components/NewResumeInput.tsx
  components/Waitlist.tsx
  components/onboarding/BaseResume.tsx
  components/onboarding/Education.tsx
  components/onboarding/EducationForm.tsx
  components/onboarding/Experience.tsx
  components/onboarding/ExperienceForm.tsx
  components/onboarding/OnboardingFormInput.tsx
  components/onboarding/PersonalDetails.tsx
  components/onboarding/PersonalDetailsForm.tsx
  components/resume/ResumeEditor.tsx
  components/resume/ResumeView.tsx
  components/resume/ResumeViewer.tsx
  components/resume/editors/EducationEditor.tsx
  components/resume/editors/ExperienceEditor.tsx
  components/resume/themes/DEAFULT_THEME/DefaultTheme.tsx
  components/resume/themes/DEAFULT_THEME/sections/EducationSection.tsx
  components/resume/themes/DEAFULT_THEME/sections/ExperienceSection.tsx
  components/resume/themes/DEAFULT_THEME/sections/PersonalInfoSection.tsx
  components/richTextEditor/components/link/link-popover-block.tsx
  components/richTextEditor/hooks/use-minimal-tiptap.ts
  constants.ts
  env.ts
  instrumentation.ts
  lib/education.methods.ts
  lib/education/actions.ts
  lib/education/types.ts
  lib/experience.methods.ts
  lib/experience/actions.ts
  lib/experience/types.ts
  lib/job/actions.ts
  lib/job/types.ts
  lib/jobs.methods.ts
  lib/personalInfo.methods.ts
  lib/resume/actions.ts
  lib/resume/types.ts
  lib/user-info/actions.ts
  lib/user-info/types.ts
  lib/utils.ts
  lib/waitlist.methods.ts
  lib/waitlist/actions.ts
  lib/waitlist/types.ts
  package.json
Labels: Core, Improvement

#101 LET-80 | core remove db operations and any signature of database from
  .env.example
  bun.lockb
  components/resume/themes/DEAFULT_THEME/DefaultTheme[Deprecated].tsx
  db/drizzle.ts
  db/education.schema.ts
  db/experience.schema.ts
  db/jobs.schema.ts
  db/personalInfo.schema.ts
  db/resumes.schema.ts
  db/schema.ts
  db/waitlist.schema.ts
  drizzle.config.ts
  env.ts
  lib/resume/actions.ts
  next.config.ts
  package.json
Labels: Core, Logic, Improvement

#105 LET-82 | chore: Remove migration files and database metadata
  migrations/0000_broken_meltdown.sql
  migrations/0001_daffy_quasar.sql
  migrations/0002_eager_tarot.sql
  migrations/0003_brave_supernaut.sql
  migrations/0004_gigantic_arachne.sql
  migrations/0005_salty_snowbird.sql
  migrations/0006_grey_wendell_rand.sql
  migrations/0007_lying_captain_america.sql
  migrations/0008_gifted_jocasta.sql
  migrations/0009_omniscient_kingpin.sql
  migrations/0010_peaceful_chronomancer.sql
  migrations/0011_fluffy_lightspeed.sql
  migrations/0012_sudden_adam_warlock.sql
  migrations/0013_redundant_moondragon.sql
  migrations/meta/0000_snapshot.json
  migrations/meta/0001_snapshot.json
  migrations/meta/0002_snapshot.json
  migrations/meta/0003_snapshot.json
  migrations/meta/0004_snapshot.json
  migrations/meta/0005_snapshot.json
  migrations/meta/0006_snapshot.json
  migrations/meta/0007_snapshot.json
  migrations/meta/0008_snapshot.json
  migrations/meta/0009_snapshot.json
  migrations/meta/0010_snapshot.json
  migrations/meta/0011_snapshot.json
  migrations/meta/0012_snapshot.json
  migrations/meta/0013_snapshot.json
  migrations/meta/_journal.json
Labels: Improvement

#103 LET-81 | ui: Implement UI improvements to the resume step of onboarding
  app/app/craft/page.tsx
  app/app/layout.tsx
  app/app/onboarding/BrainAnimation.client.tsx
  app/app/page.tsx
  components/clientContainers/AppSidebarContainer.tsx
  components/onboarding/BaseResume.tsx
  components/onboarding/EducationForm.tsx
  components/onboarding/ExperienceForm.tsx
  components/onboarding/OnboardingFormInput.tsx
  components/resume/ResumeView.tsx
  components/resume/editors/EducationEditor.tsx
  components/resume/editors/ExperienceEditor.tsx
  components/richTextEditor/components/measured-container.tsx
  components/richTextEditor/components/toolbar.tsx
  components/richTextEditor/hooks/use-minimal-tiptap.ts
  components/richTextEditor/utils.ts
  components/ui/button-group.tsx
  components/ui/input.tsx
  components/ui/select.tsx
  env.ts
  lib/constants.ts
  lib/education/types.ts
  lib/experience/types.ts
  next.config.ts
  tailwind.config.ts
Labels: Component, Layout, Style

#107 LET-83 | feat: Resume generation animation on onboarding page
  app/app/layout.tsx
  bun.lockb
  components/onboarding/Welcome.tsx
  components/providers/SmoothScrollProvider.tsx
  components/resume/ResumeView.tsx
  components/resume/ResumeViewer.tsx
  components/resume/editors/EducationEditor.tsx
  components/resume/themes/DEAFULT_THEME/DefaultTheme.tsx
  package.json
Labels: Component, Layout, Improvement
