Repository pingSubhajit/letraz, pull requests merged in 2025-03, with the labels that each got.

#108 LET 73 | core: implement the newly proposed data fetching architecture
  app/app/onboarding/page.tsx
  app/layout.tsx
  bun.lockb
  components/onboarding/Education.tsx
  components/onboarding/EducationForm.tsx
  components/onboarding/Experience.tsx
  components/onboarding/ExperienceForm.tsx
  components/onboarding/PersonalDetails.tsx
  components/onboarding/PersonalDetailsForm.tsx
  components/onboarding/Welcome.tsx
  components/providers/ApiProvider.tsx
  components/resume/ResumeView.tsx
  components/resume/ResumeViewer.tsx
  constants.ts
  lib/config/api-client.ts
  lib/config/api-types.ts
  lib/education/actions.ts
  lib/education/keys.ts
  lib/education/mutations.ts
  lib/education/queries.ts
  lib/experience/actions.ts
  lib/experience/keys.ts
  lib/experience/mutations.ts
  lib/experience/queries.ts
  lib/misc/error-handler.ts
  lib/user-info/actions.ts
  lib/user-info/keys.ts
  lib/user-info/mutations.ts
  lib/user-info/queries.ts
  package.json
Labels: enhancement, Feature, Improvement, refactor

#116 LET-84 | logic: wire backend api with education editor component
  components/resume/editors/EducationEditor.tsx
  components/resume/editors/shared/CountrySelect.tsx
  components/resume/editors/shared/DateRangeFields.tsx
  components/resume/editors/shared/EditorHeader.tsx
  components/resume/editors/shared/FormButtons.tsx
  components/resume/editors/shared/ItemCard.tsx
  components/resume/editors/shared/RichTextFormField.tsx
  components/resume/editors/shared/TextFormField.tsx
  lib/config/api-client.ts
  lib/education/actions.ts
  lib/education/mutations.ts
Labels: Logic

#117 LET-85 | logic wire backend api with experience editor component
  components/resume/editors/ExperienceEditor.tsx
  components/resume/editors/shared/DateRangeFields.tsx
  lib/experience/actions.ts
  lib/experience/mutations.ts
Labels: Component, Logic

#118 LET-89 | logic: Convert BaseResume in the onboarding to client side data fetching & revalidation
  components/onboarding/BaseResume.tsx
  components/resume/ResumeView.tsx
  components/resume/editors/EducationEditor.tsx
  components/resume/editors/ExperienceEditor.tsx
  lib/resume/key.ts
  lib/resume/queries.ts
Labels: Improvement

#121 LET-91 | comp: Remove the left sidebar animation from the app except onboarding pages
  components/clientContainers/AppSidebarContainer.tsx
Labels: Component, Logic, Improvement

#127 LET-96 | chore[deps]: Update Next.js version to 15.2.4
  bun.lockb
  package.json
Labels: Core, Improvement
