Repository pingSubhajit/letraz, pull requests merged in 2025-01, with the labels that each got.

#25 impr: Add Letraz social icons in the landing page
  app/page-footer.tsx
  app/page.tsx
  components/Waitlist.tsx
  constants.ts
Labels: Core, Improvement

#27 feat: Changes page to showcase development updates
  app/changes/PostCard.tsx
  app/changes/PostsList.tsx
  app/changes/page.heading.tsx
  app/changes/page.tsx
  app/page-footer.tsx
  app/page.tsx
  constants.ts
  declarations.d.ts
  lib/posts.method.ts
  package.json
  yarn.lock
Labels: Feature, Component, Core, Logic

#29 chore: Initial Bun migration
  bun.lockb
  package.json
  yarn.lock
Labels: Core

#21 bug: Onboarding page next and prev button overlapping elements in low height displays
  app/app/onboarding/page.tsx
  components/onboarding/About.tsx
  components/onboarding/BaseResume.tsx
  components/onboarding/Education.tsx
  components/onboarding/EducationForm.tsx
  components/onboarding/Experience.tsx
  components/onboarding/ExperienceForm.tsx
  components/onboarding/PersonalDetailsForm.tsx
  components/onboarding/Welcome.tsx
  components/providers/SmoothScrollProvider.tsx
Labels: bug

#44 chore: migrate framer motion to motiondev
  app/(auth)/signin/[[...sign-in]]/SignInPage.title.tsx
  app/(auth)/signin/[[...sign-in]]/page.tsx
  app/app/onboarding/BrainAnimation.client.tsx
  app/changes/PostCard.tsx
  app/changes/PostsList.tsx
  app/changes/page.heading.tsx
  app/page-footer.tsx
  app/page.description.tsx
  app/page.heading.tsx
  app/page.logo.tsx
  bun.lockb
  components/NewResumeInput.tsx
  components/Waitlist.tsx
  components/animations/TextAnimations.tsx
  components/auth/GithubSignInButton.tsx
  components/auth/GoogleSignInButton.tsx
  components/clientContainers/AppSidebarContainer.tsx
  components/onboarding/About.tsx
  components/onboarding/AboutDescription.tsx
  components/onboarding/Education.tsx
  components/onboarding/EducationForm.tsx
  components/onboarding/Experience.tsx
  components/onboarding/ExperienceForm.tsx
  components/onboarding/OnboardingFormInput.tsx
  components/onboarding/PersonalDetails.tsx
  components/onboarding/PersonalDetailsForm.tsx
  components/onboarding/Welcome.tsx
  components/utilities/AiLoading.tsx
  declarations.d.ts
  package.json
Labels: Core

#46 refactor(resume): Split DefaultTheme into modular components
  components/resume/ResumeViewer.tsx
  components/resume/themes/DEAFULT_THEME/DefaultTheme.tsx
  components/resume/themes/DEAFULT_THEME/DefaultTheme[Deprecated].tsx
  components/resume/themes/DEAFULT_THEME/sections/EducationSection.tsx
  components/resume/themes/DEAFULT_THEME/sections/ExperienceSection.tsx
  components/resume/themes/DEAFULT_THEME/sections/PersonalInfoSection.tsx
  components/resume/themes/DEAFULT_THEME/shared/Components.tsx
  components/resume/themes/DefaultTheme.tsx
Labels: refactor

#51 feat: New page titled "The Story Behind Letraz"
  app/story/page.content.tsx
  app/story/page.heading.tsx
  app/story/page.tsx
  constants.ts
Labels: Feature, Component

#55 feat: Website navigation menu
  app/(website)/changes/PostCard.tsx
  app/(website)/changes/PostsList.tsx
  app/(website)/changes/page.heading.tsx
  app/(website)/changes/page.tsx
  app/(website)/layout.tsx
  app/(website)/page-footer.tsx
  app/(website)/page.description.tsx
  app/(website)/page.heading.tsx
  app/(website)/page.logo.tsx
  app/(website)/page.tsx
  app/(website)/story/page.content.tsx
  app/(website)/story/page.heading.tsx
  app/(website)/story/page.tsx
  bun.lockb
  components/WebsiteNavBar.tsx
  components/ui/menu.tsx
  components/ui/sheet.tsx
  package.json
  public/nav_menu_bg.png
  routes.ts
Labels: Feature, Component, Layout

#63 feat: Accept Ghost webhook & send post to Discord bot service
  app/(website)/changes/page.heading.tsx
  app/(website)/changes/page.tsx
  app/(website)/page-footer.tsx
  app/api/update/new/route.ts
  bun.lockb
  components/Waitlist.tsx
  config.ts
  constants.ts
  lib/posts.method.ts
  package.json
Labels: Feature, Logic

#62 fix: Fix site indexing issue & update sitemap with new pages
  app/robots.ts
  app/robots.txt
  app/sitemap.ts
Labels: bug

#56 LET-40 | feat: zod validation for env
  .env.example
  components/providers/PosthogProvider.tsx
  config.ts
  db/drizzle.ts
  drizzle.config.ts
  lib/env.ts
  lib/posts.method.ts
  lib/waitlist.methods.ts
Labels: enhancement, Improvement

#80 LET-69 | fix: Zod validation fails in client side as it expects env variables to be present in client side too
  .env.example
  app/api/update/new/route.ts
  components/providers/PosthogProvider.tsx
  config.ts
  db/drizzle.ts
  drizzle.config.ts
  env.ts
  lib/posts.method.ts
  lib/waitlist.methods.ts
  next.config.mjs
  next.config.ts
Labels: bug

#85 chore[deps]: Upgrade Next.JS version to 15.1.4
  bun.lockb
  package.json
Labels: Core, Improvement

#84 LET-66 | feat: Revalidate /changes route when a new post is added to Ghost
  app/(website)/changes/page.tsx
  app/api/update/new/route.ts
Labels: Logic, Improvement

#83 LET-70 | feat: Filter out internal users in Posthog depending on the host
  components/providers/PosthogProvider.tsx
Labels: Logic, Improvement

#64 LET-48 | feat: education editor component for resume editor
  bun.lockb
  components/resume/ResumeEditor.tsx
  components/resume/editors/EducationEditor.tsx
  components/ui/command.tsx
  components/ui/tabs.tsx
  lib/constants.ts
  package.json
Labels: Feature, Component

#87 LET-63 | feat: Integrate Sentry for monitoring & issue tracking
  .env.example
  .gitignore
  app/global-error.tsx
  bun.lockb
  env.ts
  instrumentation.ts
  next.config.ts
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
Labels: Logic, Improvement

#95 LET-77 | core: Delete source-maps after upload to Sentry is finished
  next.config.ts
Labels: Layout, Core, Improvement

#94 LET-76 | core: Enable React Compiler for entire project
  app/robots.ts
  bun.lockb
  next.config.ts
  package.json
Labels: Core

#91 LET-74 | feat: ErrorView component & `/onboarding` error page
  app/(website)/page-footer.tsx
  app/(website)/page.heading.tsx
  app/app/onboarding/BrainAnimation.client.tsx
  app/app/onboarding/error.tsx
  components/onboarding/EducationForm.tsx
  components/onboarding/ExperienceForm.tsx
  components/utilities/AiLoading.tsx
  components/utilities/ErrorView.tsx
  public/error_banner.svg
Labels: Component

#97 LET-78 | feat: Landing page video and other accessibility & speed optimizations
  app/(website)/page-footer.tsx
  app/(website)/page.description.tsx
  app/(website)/page.gradientShadows.tsx
  app/(website)/page.heading.tsx
  app/(website)/page.tsx
  app/(website)/page.video.tsx
  components/Waitlist.tsx
  components/WebsiteNavBar.tsx
  public/letraz-intro.webm
Labels: Component, Improvement
